program: scripts/train.py
project: madrona-escape-room
command:
  - uv
  - run
  - python
  - ${program}
  - "--clip-value-loss"
  - "--fp16"
  - "--gpu-sim"
  - "--gpu-id"
  - "0"
  - ${args}
method: grid
parameters:
  # Core training parameters (fixed for efficiency)
  num-worlds:
    value: 4096
  num-updates:
    value: 10000
  steps-per-update:
    value: 40
  num-bptt-chunks:
    value: 8
  
  # Optimal hyperparameters from production run
  lr:
    value: 0.00038822
  gamma:
    value: 0.99
  
  # PPO tuning (optimal values)
  entropy-loss-coef:
    value: 0.005
  
  # Fixed parameters
  value-loss-coef:
    value: 0.5
  num-channels:
    value: 1024
  
  # Random seed for reproducibility
  seed:
    values: [0, 1, 2 ]
  
  # Level files for grid search across all 20 generated levels
  level-file:
    value: "levels/progressive32_spawn_random.lvl"
