program: scripts/train.py
project: madrona-escape-room
command:
  - uv
  - run
  - python
  - ${program}
  - "--eval-worlds"
  - "50"
  - "--eval-steps" 
  - "2000"
  - "--clip-value-loss"
  - "--fp16"
  - "--gpu-sim"
  - "--gpu-id"
  - "0"
  - ${args}
method: grid
parameters:
  # Core training parameters (fixed for efficiency)
  num-worlds:
    value: 4096
  num-updates:
    value: 5000
  steps-per-update:
    value: 40
  num-bptt-chunks:
    value: 8
  
  # Optimal hyperparameters from production run
  lr:
    value: 0.00038822
  gamma:
    value: 0.99
  
  # PPO tuning (optimal values)
  entropy-loss-coef:
    value: 0.005
  
  # Fixed parameters
  value-loss-coef:
    value: 0.5
  num-channels:
    value: 1024
  
  # Random seed for reproducibility
  seed:
    values: [0, 1, 2]

  # Level file (single file with lidar config passed as arguments)
  level-file:
    value: "levels/full_progression_159_levels_spawn_random.lvl"

  # Lidar configuration: Grid search across different beam counts and FOV
  lidar-num-samples:
    values: [32, 64, 128, 256]

  lidar-fov-degrees:
    values: [120.0, 180.0, 360.0]

  # Sensor noise parameters (fixed for all runs)
  lidar-noise-factor:
    value: 0.005

  lidar-base-sigma:
    value: 0.02
