program: scripts/train.py
project: madrona-escape-room
command:
  - uv
  - run
  - python
  - ${program}
  - "--clip-value-loss"
  - "--fp16"
  - "--gpu-sim"
  - "--gpu-id"
  - "0"
  - ${args}
method: grid
parameters:
  # Core training parameters (fixed for efficiency)
  num-worlds:
    value: 4096
  num-updates:
    value: 2000
  steps-per-update:
    value: 40
  num-bptt-chunks:
    value: 8
  
  # Optimal hyperparameters from production run
  lr:
    value: 0.00038822
  gamma:
    value: 0.998
  
  # PPO tuning (optimal values)
  entropy-loss-coef:
    values: [ 0.005, 0.01 ]
  
  # Fixed parameters
  value-loss-coef:
    value: 0.5
  num-channels:
    values: [256, 512]
  
  # Random seed for reproducibility
  seed:
    value: 0
  
  # Level files for grid search across all 20 generated levels
  level-file:
    values:
      - "levels/lvl1_19x48_gen.lvl"
      - "levels/lvl2_19x48_gen.lvl"
      - "levels/lvl3_19x48_gen.lvl"
      - "levels/lvl4_19x48_gen.lvl"
      - "levels/lvl5_19x48_gen.lvl"
      - "levels/lvl6_19x48_gen.lvl"
      - "levels/lvl7_19x48_gen.lvl"
      - "levels/lvl8_19x48_gen.lvl"
      - "levels/lvl9_19x48_gen.lvl"
      - "levels/lvl10_19x48_gen.lvl"
      - "levels/lvl11_19x48_gen.lvl"
      - "levels/lvl12_19x48_gen.lvl"
      - "levels/lvl13_19x48_gen.lvl"
      - "levels/lvl14_19x48_gen.lvl"
      - "levels/lvl15_19x48_gen.lvl"
      - "levels/lvl16_19x48_gen.lvl"
      - "levels/lvl17_19x48_gen.lvl"
      - "levels/lvl18_19x48_gen.lvl"
      - "levels/lvl19_19x48_gen.lvl"
      - "levels/lvl20_19x48_gen.lvl"
