"""
Auto-generated Python constants from C++ headers.
Generated by libclang AST parsing during build process.
DO NOT EDIT - this file is automatically regenerated.
"""

# ruff: noqa


class ExecMode:
    """Enum from madrona"""

    __slots__ = ()

    CPU = 0
    CUDA = 1


class ArchetypeFlags:
    """Enum from madrona"""

    __slots__ = ()

    None_ = 0  # Renamed from 'None' (Python keyword)
    ImportOffsets = 1


class ComponentFlags:
    """Enum from madrona"""

    __slots__ = ()

    None_ = 0  # Renamed from 'None' (Python keyword)
    ExportMemory = 1
    ImportMemory = 2
    CudaReserveMemory = 4
    CudaAllocMemory = 8


class SourceTextureFormat:
    """Enum from madrona.imp"""

    __slots__ = ()

    R8G8B8A8 = 0
    BC7 = 1


class Op:
    """Enum from madrona.Transaction"""

    __slots__ = ()

    Make = 0
    Destroy = 1
    Modify = 2


class Type:
    """Enum from madrona.render.LightDesc"""

    __slots__ = ()

    Directional = -1
    Spotlight = 0


class unnamed_enum_at_home_duane_madrona_escape_room_src_external_madrona_include_madrona_render_ecs_hpp_123_5:
    """Enum from madrona.render.MaterialOverride"""

    __slots__ = ()

    UseDefaultMaterial = -1
    UseOverrideColor = -2


class RenderMode:
    """Enum from madrona.render.RenderManager.Config"""

    __slots__ = ()

    RGBD = 0
    Depth = 1


class ResponseType:
    """Enum from madrona.phys"""

    __slots__ = ()

    Dynamic = 0
    Kinematic = 1
    Static = 2


class Type:
    """Enum from madrona.phys.JointConstraint"""

    __slots__ = ()

    Fixed = 0
    Hinge = 1


class Type:
    """Enum from madrona.phys.CollisionPrimitive"""

    __slots__ = ()

    Sphere = 1
    Hull = 2
    Plane = 4


class Solver:
    """Enum from madrona.phys.PhysicsSystem"""

    __slots__ = ()

    XPBD = 0
    TGS = 1


class RenderManagerConfig:
    """Constants from RenderManagerConfig namespace"""

    __slots__ = ()

    class RenderMode:
        """Enum values for RenderMode"""

        __slots__ = ()

        RGBD = 0
        Depth = 1


class Physics:
    """Constants from Physics namespace"""

    __slots__ = ()

    class ResponseType:
        """Enum values for ResponseType"""

        __slots__ = ()

        Dynamic = 0
        Kinematic = 1
        Static = 2

    class CollisionPrimitive:
        """Constants from CollisionPrimitive namespace"""

        __slots__ = ()

        class Type:
            """Enum values for Type"""

            __slots__ = ()

            Sphere = 1
            Hull = 2
            Plane = 4

    class JointConstraint:
        """Constants from JointConstraint namespace"""

        __slots__ = ()

        class Type:
            """Enum values for Type"""

            __slots__ = ()

            Fixed = 0
            Hinge = 1

    class PhysicsSystem:
        """Constants from PhysicsSystem namespace"""

        __slots__ = ()

        class Solver:
            """Enum values for Solver"""

            __slots__ = ()

            XPBD = 0
            TGS = 1

    class broadphase:
        """Constants from broadphase namespace"""

        __slots__ = ()

        class BVH:
            """Constants from BVH namespace"""

            __slots__ = ()

            sentinel_ = "0xFFFF'FFFF_i32"


__all__ = [
    "ExecMode",
    "ArchetypeFlags",
    "ComponentFlags",
    "SourceTextureFormat",
    "Op",
    "Type",
    "unnamed_enum_at_home_duane_madrona_escape_room_src_external_madrona_include_madrona_render_ecs_hpp_123_5",
    "RenderMode",
    "ResponseType",
    "Type",
    "Type",
    "Solver",
    "RenderManagerConfig",
    "Physics",
]
